name: Workspace EXE Builder

on: [push]

jobs:
  build:
    runs-on: windows-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pywebview[gui] pythonnet

      - name: Build EXE with PyInstaller
        # link.html ফাইলটিকে EXE এর ভেতরে যুক্ত করা হচ্ছে
        run: |
          pyinstaller --onefile --noconsole --add-data "link.html;." --name "Workspace_Hub" main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: Workspace-App
          path: dist/*.exe
